 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/test_environment:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/test_environment:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'test-environment'
   - '--image'
   - 'gcr.io/$PROJECT_ID/test_environment:$COMMIT_SHA'
   - '--region'
   - 'asia-southeast1'
   - '--project'
   - '$PROJECT_ID' 
   - '--platform' 
   - 'managed'
   - '--allow-unauthenticated' 
   - '--max-instances'
   - '100' 
   - '--timeout' 
   - '1800'
 images:
 - 'gcr.io/$PROJECT_ID/test_environment:$COMMIT_SHA'